---
- name: Install smartmontools
  tags: smartd
  apt:
    name: "smartmontools"

- name: Set /etc/smartd.conf
  tags: smartd
  template:
    src: smartd.conf
    dest: /etc/smartd.conf
    mode: 0644
  notify: restart smartd

